### ISSUE TITLE
Attribute Error: `dmc.NotificationsProvider` not defined.

### ISSUE THREAD

**Issue by ehrlinger** [snehilvj/dash-mantine-components#245]
After Updating to 0.14.0, it seems the NotificationsProvider has been removed.

```python
import dash_mantine_components as dmc
from dash import Dash, Input, Output, callback, html
from dash_iconify import DashIconify

"""
Wrap your layout inside a NotificationsProvider for your app.

app.layout = dmc.NotificationsProvider(
    html.Div(
        [
            html.Div(id="notifications-container"),
            dmc.Button("Show Notification", id="notify"),
        ]
    )
)
"""


layout = dmc.MantineProvider(
    dmc.NotificationsProvider(
        [
            # children
        ]
    )
)
html.Div(
    [
        html.Div(id="notifications-container"),
        dmc.Button("Show Notification", id="notify"),
    ]
)


@callback(
    Output("notifications-container", "children"),
    Input("notify", "n_clicks"),
    prevent_initial_call=True,
)
def show(n_clicks):
    return dmc.Notification(
        title="Hey there!",
        id="simple-notify",
        action="show",
        message="Notifications in Dash, Awesome!",
        icon=DashIconify(icon="ic:round-celebration"),
    )


## Define the app at the top for Dash-Enterprise
app = Dash()

app.layout = layout
# Run the app server

if __name__ == "__main__":
    app.run_server(debug=True)

```

Results in:

```shell
Traceback (most recent call last):
  File "notif.py", line 20, in <module>
    dmc.NotificationsProvider(
AttributeError: module 'dash_mantine_components' has no attribute 'NotificationsProvider'
```

**Comment by milosv-vtool** [comment]
Library moved to a newer version of mantine components, it probably got changed to just -> Notification https://mantine.dev/core/notification/

**Comment by ehrlinger** [comment]
Notification is supposed to post a Notification Dialog.

`NotificationsProvider.py` has moved to `NotificationProvider.py` However something has also changed in the call behavior. Simply changing the call name posts a JSON error `r.useSyncExternalStore` is not a function.

**Comment by snehilvj** [comment]
0.14.0 was a breaking release, just updated the docs, please have a look.

**Comment by errorcompile** [comment]
The migration guide is useful: https://www.dash-mantine-components.com/migration, as you need to set the react version to avoid the r.UseId and r.useSyncExternalStore errors.
As for the notification doc, could you fix the dmc.Notifications() typo (extra s) and add the required dmc.MantineProvider to the first example?

**Comment by ehrlinger** [comment]
Although the migration guide is helpful, and I get further, this code still  raises Dash Exceptions. 

`n.split is not a function or its return value is not iterable` is reported in the dash app debug mode. This is a JS error.

**Comment by noxthot** [comment]
Since I ran into similar problems when upgrading to dmc 0.14 and monitoring this issue did not resolve all of my issues, I tried to fix it by myself today. Now it seems to be working well.

Regarding a fix for the code snippet of the first post here. The following code should be running with 0.14.2:
```python
import dash
import dash_mantine_components as dmc
from dash import Dash, Input, Output, callback, html
from dash_iconify import DashIconify

"""
Wrap your layout inside a NotificationsProvider for your app.

app.layout = dmc.NotificationsProvider(
    html.Div(
        [
            html.Div(id="notifications-container"),
            dmc.Button("Show Notification", id="notify"),
        ]
    )
)
"""

dash._dash_renderer._set_react_version('18.2.0')  # dash mantine components need react 18

layout = dmc.MantineProvider([
        dmc.NotificationProvider(),
        html.Div(
            [
                html.Div(id="notifications-container"),
                dmc.Button("Show Notification", id="notify"),
            ]
        )
])


@callback(
    Output("notifications-container", "children"),
    Input("notify", "n_clicks"),
    prevent_initial_call=True,
)
def show(n_clicks):
    return dmc.Notification(
        title="Hey there!",
        id="simple-notify",
        action="show",
        message="Notifications in Dash, Awesome!",
        icon=DashIconify(icon="ic:round-celebration"),
    )


## Define the app at the top for Dash-Enterprise
app = Dash()

app.layout = layout
# Run the app server

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by michelkok** [comment]
> Although the migration guide is helpful, and I get further, this code still raises Dash Exceptions.
> 
> `n.split is not a function or its return value is not iterable` is reported in the dash app debug mode. This is a JS error.

Did you find a fix? I have the same error and it's very hard to find where it comes from.

**Comment by datenzauberai** [comment]
> Although the migration guide is helpful, and I get further, this code still raises Dash Exceptions.
> 
> `n.split is not a function or its return value is not iterable` is reported in the dash app debug mode. This is a JS error.

The new NotificationProvider has no children (see working example by @noxthot). This error is raised when you pass in children using a single unnamed parameter as with the provider before 0.14.
