### ISSUE TITLE
[BUG] New version not backward compatible

### ISSUE THREAD

**Issue by yxc8** [snehilvj/dash-mantine-components#246]
Hi, can you try to make your version updates backward compatible going forward? The following works in 0.12.1 but not 0.14.0. Thanks!

TypeError: The `dash_mantine_components.Menu` component (version 0.14.0) received an unexpected keyword argument: `transitionDuration` Allowed arguments: arrowOffset, arrowPosition, arrowRadius, arrowSize, boxWrapperProps, children, classNames, clickOutsideEvents, closeDelay, closeOnClickOutside, closeOnEscape, closeOnItemClick, defaultOpened, disabled, floatingStrategy, id, keepMounted, loop, menuItemTabIndex, middlewares, offset, openDelay, opened, portalProps, position, positionDependencies, radius, returnFocus, shadow, styles, transitionProps, trapFocus, trigger, unstyled, variant, width, withArrow, withinPortal, zIndex

**Comment by milosv-vtool** [comment]
This was a breaking change in the original manitne library so it is hard to preserve backwards compatibility if you want to be aligned to original lib.

Maintainers are doing a great job so far working on this and are in the process of  updating documentation, but in the mean time you can check the available options here -> https://mantine.dev/core/menu/

**Comment by snehilvj** [comment]
Hi @yxc8, I try to stay as close to official Mantine API as possible, so every time Mantine has a breaking release, dmc will break too. 

PS: Thanks @milosv-vtool
